AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DomainName:
    Description: 'Domain name'
    Type: 'String'

Mappings:
  RegionMap:
    ap-northeast-1:
      S3hostedzoneID: 'Z2M4EHUR26P7ZW'
      WebsiteEndpoint: 's3-website-ap-northeast-1.amazonaws.com'
    ap-northeast-3:
      S3hostedzoneID: 'Z2YQB5RD63NC85'
      WebsiteEndpoint: 's3-website.ap-northeast-3.amazonaws.com'

Resources:
  Route53HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Ref DomainName
      Name: !Ref DomainName

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        # ErrorDocument: 404.html

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal: '*'

  Route53RecordSet:
    DeletionPolicy: 'Retain'
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: 'A'
      AliasTarget:
        HostedZoneId: !FindInMap [ RegionMap, !Ref 'AWS::Region', S3hostedzoneID]
        DNSName: !FindInMap [ RegionMap, !Ref 'AWS::Region', WebsiteEndpoint]
      Comment: 'root domain'
